[build]
  # Build command for Vite (React)
  command = "npm run build"
  # Publish directory after build
  publish = "dist"

[dev]
  # Optional: local dev server configuration
  command = "npm run dev"
  port = 5173
  targetPort = 5173
  framework = "vite"

# Optional: Redirects for single-page apps (React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
